name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # - name: Run tests
      #   run: deno test

      - name: Is Release?
        if: startswith(github.ref, 'refs/tags/v')
        run: echo "DEPLOY_PACKAGE=true" >> $GITHUB_ENV

      - name: Publish to npm
        if: env.DEPLOY_PACKAGE == 'true'
        run: npx jsr publish
