name: Release apex version

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: denolib/setup-deno@v2
      - name: Update version and README.md
        env:
          VERSION: ${{ inputs.version }}
          FILES: 'mod.ts,README.md'
        run: |
          deno run --allow-run --allow-env --allow-write --allow-read ./.github/workflows/release.ts
          deno run --allow-run --allow-env --allow-write --allow-read ./.github/workflows/update-readme.ts
      - name: Commit and tag release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.version }} release
          tagging_message: ${{ inputs.version }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ inputs.version }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # - name: Run tests
      #   run: deno test

      - name: Is Release?
        if: startswith(github.ref, 'refs/tags/v')
        run: echo "DEPLOY_PACKAGE=true" >> $GITHUB_ENV

      - name: Publish to npm
        if: env.DEPLOY_PACKAGE == 'true'
        run: npx jsr publish
