name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run tests
        run: just test
